name: SaxonHE CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  tags:
    - '*'

jobs:
  main:
    runs-on: windows-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Choco pack
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: pack
      -
        name: Choco test install
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install SaxonHE -s .
      -
        name: Choco test uninstall
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: uninstall SaxonHE
      - 
        name: Upload choco package
        uses: actions/upload-artifact@v2
        with:
          path: SaxonHE*.nupkg