name: SaxonHE CI

on:
  push:
    branches: [ master ]
    tags:
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  main:
    runs-on: windows-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Choco pack
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: pack
      -
        name: Choco test install
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install SaxonHE -s .
      -
        name: Choco test uninstall
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: uninstall SaxonHE
      - 
        name: Upload choco package
        uses: actions/upload-artifact@v2
        with:
          path: SaxonHE*.nupkg
      - 
        name: Display var
        env:
          SUPER_SECRET: ${{ secrets.CHOCO_API_KEY }}
        run: |
          echo "${env:SUPER_SECRET}"
      - 
        name: Display var2
        env:
          SUPER_SECRET: ${{ secrets.CHOCO_API_KEY }}
        run: |
          echo "${$env:SUPER_SECRET}"
      - 
        name: Display var3
        env:
          SUPER_SECRET: ${{ secrets.CHOCO_API_KEY }}
        run: |
          echo "$(env:SUPER_SECRET)"
      - 
        name: Display var4
        env:
          SUPER_SECRET: ${{ secrets.CHOCO_API_KEY }}
        run: |
          echo "$($env:SUPER_SECRET)"
      - 
        name: Display var5
        env:
          SUPER_SECRET: ${{ secrets.CHOCO_API_KEY }}
        run: |
          echo "%SUPER_SECRET%"
      - 
        name: Display var6
        env:
          SUPER_SECRET: ${{ secrets.CHOCO_API_KEY }}
        run: |
          echo "$SUPER_SECRET"
      - 
        name: Push choco package
        uses: crazy-max/ghaction-chocolatey@v1
        env:
          CHOCO_API_KEY: ${{ secrets.CHOCO_API_KEY }}
        with:
          args: push -y -k $env:CHOCO_API_KEY